"""add username hardware metrics firewall logs

Revision ID: fcaac66924ad
Revises: 94aa680a19c8
Create Date: 2026-06-08 15:18:37.394423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaac66924ad'
down_revision = '94aa680a19c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('flow_iat_mean', sa.Float(), nullable=True),
    sa.Column('tot_fwd_pkts', sa.Integer(), nullable=True),
    sa.Column('pkt_size_avg', sa.Float(), nullable=True),
    sa.Column('flow_duration', sa.Float(), nullable=True),
    sa.Column('selected_model', sa.String(length=100), nullable=True),
    sa.Column('selected_score', sa.Float(), nullable=True),
    sa.Column('all_model_scores', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.Column('app_package', sa.String(length=200), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('ram_used_mb', sa.Integer(), nullable=False),
    sa.Column('ram_total_mb', sa.Integer(), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_system_traffic', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('log_system_traffic')

    op.drop_table('hardware_metrics')
    op.drop_table('firewall_logs')
    # ### end Alembic commands ###
