"""update firewall logs schema

Revision ID: fe31bd54168d
Revises: fcaac66924ad
Create Date: 2026-06-13 20:56:36.485582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe31bd54168d'
down_revision = 'fcaac66924ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dst_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('packet_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iat_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iat_std', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fwd_pkts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bwd_pkts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fwd_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fwd_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fwd_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('idle_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prob_brute', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prob_dos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prob_adv_dos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prob_loic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prob_hoic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('top_threat_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_attack_prob', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('action_taken', sa.String(length=15), nullable=False))
        batch_op.drop_column('action')
        batch_op.drop_column('threat_type')
        batch_op.drop_column('tot_fwd_pkts')
        batch_op.drop_column('selected_model')
        batch_op.drop_column('selected_score')
        batch_op.drop_column('flow_iat_mean')
        batch_op.drop_column('created_at')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('flow_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flow_iat_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selected_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selected_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tot_fwd_pkts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('threat_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('action_taken')
        batch_op.drop_column('max_attack_prob')
        batch_op.drop_column('top_threat_type')
        batch_op.drop_column('prob_hoic')
        batch_op.drop_column('prob_loic')
        batch_op.drop_column('prob_adv_dos')
        batch_op.drop_column('prob_dos')
        batch_op.drop_column('prob_brute')
        batch_op.drop_column('idle_mean')
        batch_op.drop_column('fwd_mean')
        batch_op.drop_column('fwd_rate')
        batch_op.drop_column('fwd_max')
        batch_op.drop_column('bwd_pkts')
        batch_op.drop_column('fwd_pkts')
        batch_op.drop_column('iat_std')
        batch_op.drop_column('iat_mean')
        batch_op.drop_column('duration')
        batch_op.drop_column('packet_size')
        batch_op.drop_column('dst_ip')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
