"""create initial database tables

Revision ID: 94aa680a19c8
Revises: 
Create Date: 2026-05-12 19:22:32.520712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94aa680a19c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('acl_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip', name='unique_acl_user_ip')
    )
    op.create_table('blacklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.Column('bf_score', sa.Float(), nullable=True),
    sa.Column('dos_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip', name='unique_blacklist_user_ip')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('unknown_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('flow_iat_mean', sa.Float(), nullable=True),
    sa.Column('tot_fwd_pkts', sa.Integer(), nullable=True),
    sa.Column('pkt_size_avg', sa.Float(), nullable=True),
    sa.Column('flow_duration', sa.Float(), nullable=True),
    sa.Column('bf_score', sa.Float(), nullable=True),
    sa.Column('dos_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('block_threshold', sa.Float(), nullable=True),
    sa.Column('warn_threshold', sa.Float(), nullable=True),
    sa.Column('flood_detection', sa.Boolean(), nullable=True),
    sa.Column('syn_flood_detection', sa.Boolean(), nullable=True),
    sa.Column('flood_pkt_per_sec', sa.Integer(), nullable=True),
    sa.Column('syn_flood_per_sec', sa.Integer(), nullable=True),
    sa.Column('bf_model_enabled', sa.Boolean(), nullable=True),
    sa.Column('dos_model_enabled', sa.Boolean(), nullable=True),
    sa.Column('max_log_entries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('training_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('flow_iat_mean', sa.Float(), nullable=True),
    sa.Column('tot_fwd_pkts', sa.Integer(), nullable=True),
    sa.Column('pkt_size_avg', sa.Float(), nullable=True),
    sa.Column('flow_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['unknown_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_samples')
    op.drop_table('user_settings')
    op.drop_table('unknown_events')
    op.drop_table('refresh_tokens')
    op.drop_table('model_versions')
    op.drop_table('blacklist_entries')
    op.drop_table('acl_entries')
    op.drop_table('users')
    # ### end Alembic commands ###
